mode: "dev"
port: 8765

log:
  level: "debug"
  filename: "./log/bluebell-%s.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.11"
  port: "33069"
  user: "root"
  password: "123456"
  db: "bluebell_pre"
  max_open_conns: 100
  max_idle_conns: 20